name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: yarn
      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{EMAIL_GITHUB}}
          git config --global user.name ${{USERNAME_GITHUB}}
          git remote set-url origin https://${{TOKEN_GITHUB}}@github.com/${{USERNAME_GITHUB}}/apollos-playlist.git
          REACT_APP_SPOTIFY_CLIENT_ID=${{CLIENT_ID}} yarn deploy
